'use server';
import {revalidatePath} from 'next/cache';import {redirect} from 'next/navigation';import {prisma} from '@/lib/prisma';import {getSession,requireAdmin} from '@/lib/auth';import {Prisma,TransactionType} from '@prisma/client';
const str=(f:FormData,k:string)=>String(f.get(k)||'').trim(), num=(f:FormData,k:string)=>Number(f.get(k)||0);
export async function createVehicle(f:FormData){if(!await getSession())throw new Error('Não autorizado');const customerId=str(f,'customerId'),plate=str(f,'plate').toUpperCase();if(!customerId||!plate)throw new Error('Cliente e placa são obrigatórios.');await prisma.vehicle.create({data:{customerId,plate,brand:str(f,'brand'),model:str(f,'model'),year:num(f,'year')||null,color:str(f,'color'),mileage:num(f,'mileage'),fuel:str(f,'fuel'),chassis:str(f,'chassis')||null,notes:str(f,'notes')}});revalidatePath('/veiculos');redirect('/veiculos')}
export async function createService(f:FormData){if(!await getSession())throw new Error('Não autorizado');const price=num(f,'defaultPrice');if(price<0)throw new Error('Valor inválido.');await prisma.service.create({data:{name:str(f,'name'),description:str(f,'description'),defaultPrice:new Prisma.Decimal(price),active:f.get('active')==='on'}});revalidatePath('/servicos')}
export async function createProduct(f:FormData){if(!await getSession())throw new Error('Não autorizado');const quantity=num(f,'quantity'),minimumStock=num(f,'minimumStock'),costPrice=num(f,'costPrice'),salePrice=num(f,'salePrice');if([quantity,minimumStock,costPrice,salePrice].some(v=>v<0))throw new Error('Quantidade e valores não podem ser negativos.');await prisma.product.create({data:{code:str(f,'code'),name:str(f,'name'),category:str(f,'category'),brand:str(f,'brand'),quantity,minimumStock,costPrice:new Prisma.Decimal(costPrice),salePrice:new Prisma.Decimal(salePrice),supplier:str(f,'supplier')}});revalidatePath('/estoque')}
export async function moveStock(f:FormData){if(!await getSession())throw new Error('Não autorizado');const productId=str(f,'productId'),quantity=num(f,'quantity'),type=str(f,'type') as 'ENTRADA'|'SAIDA';if(quantity<=0)throw new Error('Quantidade deve ser positiva.');await prisma.$transaction(async tx=>{const p=await tx.product.findUniqueOrThrow({where:{id:productId}});if(type==='SAIDA'&&p.quantity<quantity)throw new Error('Estoque insuficiente.');await tx.product.update({where:{id:productId},data:{quantity:type==='ENTRADA'?{increment:quantity}:{decrement:quantity}}});await tx.stockMovement.create({data:{productId,type,quantity,reason:str(f,'reason')||'Movimentação manual'}})});revalidatePath('/estoque')}
export async function createTransaction(f:FormData){await requireAdmin();const amount=num(f,'amount');if(amount<=0)throw new Error('Informe um valor positivo.');await prisma.financialTransaction.create({data:{description:str(f,'description'),category:str(f,'category'),type:str(f,'type') as TransactionType,amount:new Prisma.Decimal(amount),date:new Date(str(f,'date')+'T12:00:00'),paymentMethod:str(f,'paymentMethod'),notes:str(f,'notes')}});revalidatePath('/financeiro')}
export async function saveSettings(f:FormData){await requireAdmin();await prisma.workshopSettings.upsert({where:{id:'default'},create:{id:'default',name:str(f,'name'),document:str(f,'document'),phone:str(f,'phone'),whatsapp:str(f,'whatsapp'),email:str(f,'email'),address:str(f,'address'),city:str(f,'city'),state:str(f,'state'),logoUrl:str(f,'logoUrl'),receiptText:str(f,'receiptText'),orderText:str(f,'orderText')},update:{name:str(f,'name'),document:str(f,'document'),phone:str(f,'phone'),whatsapp:str(f,'whatsapp'),email:str(f,'email'),address:str(f,'address'),city:str(f,'city'),state:str(f,'state'),logoUrl:str(f,'logoUrl'),receiptText:str(f,'receiptText'),orderText:str(f,'orderText')}});revalidatePath('/configuracoes')}
